name: Deploy to Tomcat
hosts: web
become: yes
tasks:
	name: Copy WAR file to Tomcat
	copy:
		src: "/var/snap/jenkins/4874/workspace/MavenWeb5-CICD/target/MavenWeb5.war"
		dest: "/opt/tomcat/webapps/MavenWeb5.war"
		remote_src: no
	name: Restart Tomcat
	systemd:
		name: tomcat
		state: restart
